### PR TITLE
Bump Gitlab Version to 8.16.6

### PR DESCRIPTION
**Pull request by davidkudera**
* [x] Configure `GITLAB_SECRETS_SECRET_KEY_BASE`
* [x] Configure `GITLAB_SECRETS_OTP_KEY_BASE`

### CODE REVIEW

**Comment by davidkudera** [comment]
Hello, I updated gitlab to latest available stable version. 

I have only problem with secrets variables. Ideally they should be autogenerated before the first run with some minimum length. Is there any way how I could improve it or should we keep it like it is now?

Thanks

**Comment by iMarkus** [comment]
Current version is 10.1.1, how about that?

**Comment by fcwu** [comment]
Hi we are going to release new version soon. Please stay tune.

**Comment by iMarkus** [comment]
@fcwu thanks. I modified the docker-compose.yaml on my own and everything works fine with 10.1.1

Looking forward to use the new version provided by QNAP. Which version are you going to provide?

**Comment by fcwu** [comment]
@iMarkus it's 10.0.4 in DQV verifying.

**Comment by iMarkus** [comment]
@fcwu Any update on this topic?

**Comment by fcwu** [comment]
soon. DQV will start to verify in couple of days.

**Comment by walkerlee** [comment]
gitlab 10.0.4 already release

**Pull request closed without merging**
